impression_index:
    pattern: /impression
    defaults: { _controller: ApplicationSonataClientBundle:Impression:index }

impression_etiquette:
    pattern: /impression/etiquette
    defaults: { _controller: ApplicationSonataClientBundle:Impression:etiquette }


initial_import_index:
    pattern: /initial-import
    defaults: { _controller: ApplicationSonataClientBundle:InitialImport:index }

initial_import_client:
    pattern: /initial-import-client
    defaults: { _controller: ApplicationSonataClientBundle:InitialImport:client }
