services:
  application.sonata.admin.impots:
     class : Application\Sonata\ImpotsBundle\Admin\ImpotsAdmin
     tags:
          - { name: sonata.admin, manager_type: orm, group: Centre des Impôts, label: Centre des Impôts }
     arguments: [null, Application\Sonata\ImpotsBundle\Entity\Impots, ApplicationSonataImpotsBundle:Impots]
